spring:
 profiles:
  active:
  - dev
  
---
spring:
 profiles: dev
 application: 
  name: microservicecloud_config_atguigu_dev 
  
---
spring:
 profiles: test
 application: 
  name: microservicecloud_config_atguigu_test 